api/urls.py
from django.urls import  include, path
from rest_framework import routers
from api.quickstart import views
 
router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'platos', views.PlatoViewSet)
router.register(r'tipoplatos', views.TipoPlatoViewSet)
router.register(r'galeria', views.GaleriaViewSet)
router.register(r'reservacion', views.ReservacionViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.seccion_home, name='home'),

]

lacasonadetoko/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as user_views

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls, name='admin'),
    path('', include('home.urls', namespace='home')),
    path('reservas/', include('reservacion.urls', namespace='reserva')),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/login.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    path('api/', include('api.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "La Casona de Toko - AdminPanel"
admin.site.site_title = "Restaurant App Admin"
admin.site.site_index_title = "Bienvenido a la Casona de Toko Admin Panel"

reservacion/urls.py
from django.urls import path
from . import views

app_name = 'reservacion'

urlpatterns = [
    path('', views.reserva_mesa, name='reserva_mesa'),
]

home/models.py
from django.db import models

# Create your models here.

# SECCION NOSOTROS
class Nosotros(models.Model):
    descripcion = models.TextField()

    class Meta:
        verbose_name = 'Nosotros'
        verbose_name_plural = 'Nosotros'

    def __str__(self):
        return self.descripcion


class Contenido(models.Model):
    titulo = models.CharField(max_length=50)
    imagen = models.ImageField(upload_to='nosotros/')
    descripcion = models.TextField()

    class Meta:
        verbose_name = 'Contenido'
        verbose_name_plural = 'Contenido'
        ordering = ["-titulo"]

    def __str__(self):
        return self.titulo

# SECCION CARTA
class Plato(models.Model):
    nombre = models.CharField(max_length=50, verbose_name='Nombre del Plato')
    precio = models.IntegerField(default=0, verbose_name='Precio')
    tipo_plato = models.ForeignKey(
        'TipoPlato', on_delete=models.SET_NULL, null=True, verbose_name='Tipo de Plato')
    

    class Meta:
        verbose_name = 'Plato'
        verbose_name_plural = 'Platos'
        ordering = ["tipo_plato"]

    def __str__(self):
        return self.nombre


class TipoPlato(models.Model):
    nombre = models.CharField(max_length=50, verbose_name='Tipo de Plato')

    class Meta:
        verbose_name = 'Tipo de Plato'
        verbose_name_plural = 'Tipos de Plato'
        

    def __str__(self):
        return self.nombre


# SECCION GALERIA
class Galeria(models.Model):
    titulo = models.CharField(max_length=50)
    imagen = models.ImageField(upload_to='galeria/')

    class Meta:
        verbose_name = 'Galeria'
        verbose_name_plural = 'Galeria'
        ordering = ["-titulo"]

    def __str__(self):
        return self.titulo

home/views.py
from django.shortcuts import render
from .models import Nosotros, Contenido, Galeria, Plato, TipoPlato

# Create your views here.

# View Nosotros

def seccion_home(request):
    nosotros = Nosotros.objects.all()
    contenido = Contenido.objects.all()
    galeria = Galeria.objects.all()
    plato = Plato.objects.all()
    tipo_plato = TipoPlato.objects.all()

    context = {
        'nosotros': nosotros,
        'contenido': contenido,
        'plato': plato,
        'galeria': galeria,
        'tipo_plato': tipo_plato,
    }

    return render(request, 'home/index.html', context)

home/templates/home/index.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
    <!-- Carrusel -->
    <div id="carrusel" class="carousel slide carousel-fade" data-rode="carousel">
        <ul class="carousel-indicators">
            <li data-target="#carrusel" data-slide-to="0" class="active"></li>
            <li data-target="#carrusel" data-slide-to="1"></li>
            <li data-target="#carrusel" data-slide-to="2"></li>
        </ul>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="img1" src="{% static 'img/carrusel/back1.jpg' %}" alt="b1">
                <div class="carousel-caption">
                    <h2 class="display-3">Bienvenidos A</h2>
                    <h1 class="display-1">La Casona De Toko</h1>
                    <h3>El Sabor De La Comida Chilena Directo A Tu Mesa</h3>
                    <a href="{% url 'reservacion:reserva_mesa' %}" class="btn btn-danger btn-lg">Reserva Tu Mesa</a>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/carrusel/back2.jpg' %}" alt="b3">
                <div class="carousel-caption">
                    <h2 class="display-3">Disfruta de una Comida</h2>
                    <h1 class="display-1">Hecha con Carino y Dedicacion</h1>
                    <a href="{% url 'reservacion:reserva_mesa' %}" class="btn btn-danger btn-lg">Reserva Tu Mesa</a>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/carrusel/back4.jpg' %}" alt="b4">
                <div class="carousel-caption">
                    <h2 class="display-3">Sabores Tradicionales</h2>
                    <h1 class="display-1">Llenos de Historia</h1>
                    <a href="{% url 'reservacion:reserva_mesa' %}" class="btn btn-danger btn-lg">Reserva Tu Mesa</a>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carrusel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carrusel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <!-- End-->

    <!-- Nosotros -->
    <section id="nosotros">
        <div class="container-fluid padding">
            <div class="row nosotros text-center">
                <div class="col-12">
                    <h2 class="display-4">Sobre Nosotros</h2>
                    <hr>
                    {% for nosotros in nosotros %}
                    <div class="col-12">
                        <p class="lead">
                            {{nosotros.descripcion}}
                        </p>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="row nosotros text-center padding">
                {% for contenido in contenido %}
                    <div class="col-xs-12 col-sm-6 col-md-4">
                        <img class="img-fluid" src="{{contenido.imagen.url}}" alt="{{contenido.titulo}}">
                        <h3>{{contenido.titulo}}</h3>
                        <p>{{contenido.descripcion}}</p>
                    </div>
                {% endfor %}
                <hr>
            </div>
        </div>
    </section>
    <!-- End-->

    <!-- Seccion Parallax -->
    <div id="p1" class="parallax">
        <div class="fixed-wrap">
            <div class="fixed-1">
            </div>
        </div>
    </div>
    <!-- End-->

    <!-- Carta -->
     <section id="carta">
         <div class="container-fluid padding">
             <div class="row carta text-center">
                 <div class="col-12">
                     <h2 class="display-4">Carta</h2>
                     <hr>
                 </div>
             </div>

             <div class="row carta-content">
                 <div class="col-12">
                     <div class="carta-left">
                         <nav class="nav nav-pills nav-fill mb-3">
                             {% for tipo_plato in tipo_plato %}
                             {% if forloop.first %}
                             <a class="nav-item nav-link active" data-toggle="pill"
                                 href="#{{tipo_plato}}">{{tipo_plato.nombre}}</a>
                             {% else %}
                             <a class="nav-item nav-link" data-toggle="pill"
                                 href="#{{tipo_plato}}">{{tipo_plato.nombre}}</a>
                             {% endif %}
                             {% endfor %}
                         </nav>

                         <div class="tab-content">
                             {% for tipo_plato in tipo_plato %}
                             {% if forloop.first %}
                             <div id="{{tipo_plato}}" class="tab-pane fade show active">
                                 <h3>{{tipo_plato.nombre}}</h3>
                                 {% for plato in plato %}
                                 {% if plato.tipo_plato == tipo_plato %}
                                 <ul>
                                     <li>{{plato.nombre}} <span>$ {{plato.precio|intcomma}}</span>
                                         <hr>
                                     </li>
                                 </ul>
                                 {% endif %}
                                 {% endfor %}
                             </div>
                             {% else %}
                             <div id="{{tipo_plato}}" class="tab-pane fade show">
                                 <h3>{{tipo_plato.nombre}}</h3>
                                 {% for plato in plato %}
                                 {% if plato.tipo_plato == tipo_plato %}
                                 <ul>
                                     <li>{{plato.nombre}} <span>$ {{plato.precio|intcomma}}</span>
                                         <hr>
                                     </li>
                                 </ul>
                                 {% endif %}
                                 {% endfor %}
                             </div>
                             {% endif %}
                             {% endfor %}
                         </div>
                     </div>
                 </div>
                 <hr>
             </div>
         </div>
     </section>
    <!-- End-->

    <!-- Seccion Parallax -->
    <div id="p2" class="parallax">
        <div class="fixed-wrap">
            <div class="fixed-2">
            </div>
        </div>
    </div>
    <!-- End-->

    <!-- Galeria -->
    <section id="galeria">
        <div class="container-fluid padding">
            <div class="row galeria text-center">
                <div class="col-12">
                    <h2 class="display-4">Galeria</h2>
                    <hr>
                </div>
            </div>

            <div class="gal-cont">
                <div class="row no-padding">
                    {% for galeria in galeria %}
                    <div class="col-sm-4">
                        <div class="gal-img">
                            <a class="lightbox" href="{{ galeria.imagen.url }}"><img src="{{ galeria.imagen.url }}"
                                    alt="{{galeria.titulo}}"></a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
    <!-- End-->

    <!-- Seccion Parallax -->
    <div id="p3" class="parallax">
        <div class="fixed-wrap">
            <div class="fixed-3">
            </div>
        </div>
    </div>
    <!-- End-->

    <!-- Ubicacion -->
    <section id="ubicacion">
        <div class="container-fluid padding">
            <div class="row ubicacion text-center">
                <div class="col-12">
                    <h2 class="display-4">Ubicacion</h2>
                    <hr>
                </div>
            </div>
            <div class="row ubi-map visible">
                <div class="col-md-12">
                    <iframe
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d16202.754099577829!2d-70.66460200000002!3d-33.45224900000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662c501408bc3d5%3A0x35f6afab29cafdee!2sAlmirante%20Latorre%20357%2C%20Santiago%2C%20Regi%C3%B3n%20Metropolitana!5e1!3m2!1ses-419!2scl!4v1567399633690!5m2!1ses-419!2scl">
                    </iframe>
                </div>
            </div>
        </div>
    </section>
    <!-- End-->
{% endblock content %}