accounts/urls.py
from . import views

api/urls.py
from django.urls import  include, path
from rest_framework import routers
from api.quickstart import views
 
router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'platos', views.PlatoViewSet)
router.register(r'tipoplatos', views.TipoPlatoViewSet)
router.register(r'galeria', views.GaleriaViewSet)
router.register(r'reservacion', views.ReservacionViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.seccion_home, name='home'),

]

lacasonadetoko/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as user_views

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls, name='admin'),
    path('', include('home.urls', namespace='home')),
    path('reservas/', include('reservacion.urls', namespace='reserva')),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/login.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    path('api/', include('api.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "La Casona de Toko - AdminPanel"
admin.site.site_title = "Restaurant App Admin"
admin.site.site_index_title = "Bienvenido a la Casona de Toko Admin Panel"

accounts/views.py
from django.shortcuts import render, redirect, render_to_response

# # Create your views here.

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<section id="login">
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <h5 class="card-title text-center">Iniciar Sesion</h5>
                        <form class="form-signin" method="POST">
                            {% csrf_token %}
                            <div class="form-label-group">
                                {{form|crispy}}
                                <br>
                                {% if request.GET.next %}
                                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                                {% endif %}
                                <button class="btn btn-lg btn-danger btn-block text-uppercase" type="submit">Iniciar
                                    Sesion</button>

                                <div class="texto text-center">
                                    <a class="small" href="{% url 'password_reset' %}">¿Has olvidado tu contrasena?</a>
                                </div>
                                {% comment %}
                                <hr class="my-4">
                                <button class="btn btn-lg btn-google btn-block text-uppercase" type="submit"><i
                                        class="fab fa-google mr-2"></i> Iniciar con Google
                                </button>
                                <button class="btn btn-lg btn-facebook btn-block text-uppercase" type="submit"><i
                                        class="fab fa-facebook-f mr-2"></i> Iniciar con Facebook
                                </button> {% endcomment %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

accounts/templates/accounts/password_reset.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<section id="login">
    <br>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <h5 class="card-title text-center">Recuperar tu Contrasena</h5>
                        <br>
                        <form class="form-signin" method="POST">
                            {% csrf_token %}
                            <div class="form-label-group">
                                {{form|crispy}}
                            </div>
                            <br>
                            <br>
                            <button class="btn btn-lg btn-danger btn-block text-uppercase" type="submit">Enviar Mail de
                                Recuperacion</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<section id="login">
    <br>
    <br>
    <br>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <h5 class="card-title text-center">Recuperacion de Contrasena Completada.</h5>
                        <br>
                        <div class="alert alert-info">
                            Se ha recuperado la contrasena de la cuenta de manera exitosa.
                        </div>
                        <br>
                        <div class="form-signin">
                            <button class="btn btn-lg btn-danger btn-block text-uppercase"
                                onclick="location.href='{% url 'login' %}'">Volver al Login</button>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<section id="login">
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <h5 class="card-title text-center">Recuperar tu Contrasena</h5>
                        <br>
                        <form class="form-signin" method="POST">
                            {% csrf_token %}
                            <div class="form-label-group">
                                {{form|crispy}}
                            </div>
                            <br>
                            <br>

                            <button class="btn btn-lg btn-danger btn-block text-uppercase" type="submit">Reestablecer
                                Contrasena</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<section id="login">
    <br>
    <br>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <h5 class="card-title text-center">Mail de Recuperacion Enviado</h5>
                        <br>
                        <div class="alert alert-info">
                            Se ha enviado un mail con instrucciones para la recuperacion de su contrasena.
                        </div>
                        <br>
                        <br>
                        <div class="form-signin">
                            <button class="btn btn-lg btn-danger btn-block text-uppercase"
                                onclick="location.href='{% url 'home:home' %}'">Volver al Inicio</button>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}